import fs from 'node:fs/promises';
import path from 'node:path';
import { Storage } from 'megajs';

const url = process.env.MEGA_FOLDER_URL;
if (!url) throw new Error('MEGA_FOLDER_URL is required');
const out = process.env.OUTPUT_DIR || 'dist';
const storage = await new Storage({});
await new Promise((resolve, reject) => { storage.on('ready', resolve); storage.on('error', reject); });
const folder = await storage.root.link(url).loadAttributes().catch(() => null);
if (!folder) throw new Error('Unable to open Mega folder');
const children = folder.children || [];
const candidates = children.filter(x => /秋城落叶/.test(x.name) && !/(底包|base|firmware)/i.test(x.name));
if (!candidates.length) throw new Error('No 秋城落叶 ROM found');
candidates.sort((a,b) => (b.timestamp||0) - (a.timestamp||0) || b.name.localeCompare(a.name));
const file = candidates[0];
await fs.mkdir(out, {recursive:true});
const target = path.join(out, file.name);
await new Promise((resolve, reject) => file.download().pipe(require('node:fs').createWriteStream(target)).on('finish', resolve).on('error', reject));
console.log(`Downloaded ${file.name} -> ${target}`);
